[".config/bat/themes/Catppuccin Frappe.tmTheme"]
    type = "file"
    url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme"

[".config/bat/themes/Catppuccin Latte.tmTheme"]
    type = "file"
    url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
