{{- $unameMachine := output "uname" "-m" | trim -}}
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/fd"]
    type = "archive-file"
    path = "fd"
    executable = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/fd" (printf "fd-v*-%s-unknown-linux-musl.tar.gz" $unameMachine) | quote }}

[".config/fish/completions/fd.fish"]
    type = "archive-file"
    path = "autocomplete/fd.fish"
    stripComponents = 1
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "sharkdp/fd" (printf "fd-v*-%s-unknown-linux-musl.tar.gz" $unameMachine) | quote }}
{{- end }}
