{{- if and (eq .chezmoi.os "linux") (eq .chezmoi.osRelease.id "fedora") }}
[".local/share/icons/hicolor/scalable/apps/ptyxis.svg"]
    type = "file"
    url = "https://gitlab.gnome.org/chergert/ptyxis/-/raw/main/data/icons/ptyxis.svg"
{{ end }}
