{{- $unameMachine := output "uname" "-m" | trim -}}
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/rg"]
    type = "archive-file"
    path = "rg"
    executable = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" (printf "ripgrep-*-%s-unknown-linux-*.tar.gz" $unameMachine) | quote }}

[".local/share/man/man1/rg.1"]
    type = "archive-file"
    path = "doc/rg.1"
    stripComponents = 1
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" (printf "ripgrep-*-%s-unknown-linux-*.tar.gz" $unameMachine) | quote }}
{{- end }}
