{{- $unameMachine := output "uname" "-m" | trim -}}
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/starship"]
    type = "archive-file"
    path = "starship"
    executable = true
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "starship/starship" (printf "starship-%s-unknown-linux-musl.tar.gz" $unameMachine) | quote }}
{{- end }}
