[fedora-distrobox-42]
image=quay.io/fedora/fedora-toolbox:42
additional_packages="age bat cargo clojure fastfetch fish fortune-mod gcc gdb gh golang guile30 janet lazygit neovim nodejs npm opam regina ripgrep sqlite"
pre_init_hooks="dnf copr enable atim/lazygit -y"
init_hooks="curl -sS https://starship.rs/install.sh | sh -s -- -y"
init_hooks="go install golang.org/x/tools/gopls@latest"
exported_bins="/usr/bin/go /usr/bin/age /usr/bin/age-keygen /usr/bin/cargo /usr/bin/lazygit /usr/bin/npm /usr/bin/opam"
exported_bins_path="$HOME/.local/bin"


[alpine-distrobox-edge]
image=quay.io/toolbx-images/alpine-toolbox:edge
additional_packages="fastfetch fish fortune neovim starship"


#[ubuntu-distrobox-plucky]
#image=quay.io/toolbx/ubuntu-toolbox:25.04 
#pre_init_hooks="dpkg --add-architecture i386"
#pre_init_hooks="mkdir -pm755 /etc/apt/keyrings"
#pre_init_hooks="wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -"
#pre_init_hooks="wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/plucky/winehq-plucky.sources"
#additional_packages="fastfetch fish fortune neovim starship winehq-staging"
#
