GUIX_DAEMON_SOCKET=guix://127.0.0.1:44146
GUIX_PROFILE="${HOME}/.guix-profile"
GUIX_CURRENT="${HOME}/.config/guix/current"
PATH="${GUIX_CURRENT}/bin:${GUIX_PROFILE}/bin:${PATH}"
INFOPATH="${HOME}/.guix-profile/share/info:"
MANPATH="${HOME}/.guix-profile/share/man:"
