" Disable strict `vi` compatibility.
set nocp

" Do not allow ':autocmd', shell or write commands in '.exrc' files found in
" the current directory and display map commands.
set secure

" Enable statusline
set laststatus=2

" Enable syntax highlighting
syntax on

" Enable relative line numbers
set nu rnu

" et: Use the appropriate number of spaces to insert a '<Tab>' in Insert mode.
set et

" ai: Copy indent from current line when starting a new line.
" si: Do smart autoindenting when starting a new line.
" sm: When a bracket is inserted, briefly jump to the matching one.
set ai si sm

" ic: Searches should ignore case.
set ic

" Map the key sequence 'jk' to '<ESC>' in Insert mode.
ino jk <esc>

" Package configuration:
call plug#begin()

Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'itchyny/lightline.vim'
"Plug 'sheerun/vim-polyglot'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-sleuth'

call plug#end()

" Enable true color support.
set termguicolors

" Set vim and lightline colorschemes.
let g:lightline = {'colorscheme': 'catppuccin_frappe'}
silent! colorscheme catppuccin_frappe

" Emphasize text of current line & customize line number colors.
set cursorline
hi LineNr ctermfg=8
hi CursorLineNr ctermfg=7 term=bold cterm=bold

" Enable `vim-indent-guides`.
let g:indent_guides_guide_size = 1
let g:indent_guides_enable_on_vim_startup = 1

" Fold code by syntax.
set foldmethod=syntax
set nofoldenable
